INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('patricia', 'johnson', 'patriciajohnson@guvi.in', 'Legal', 25000, '2019-11-25');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('linda', 'williams', 'lindawilliams@guvi.in', 'IT', 95000, '2021-03-25');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('barbara', 'jones', 'barbarajones@guvi.in', 'Human Resources', 45000, '2011-08-12');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('elizabeth', 'brown', 'elizabethbrown@guvi.in', 'IT', 36000, '2022-03-18');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('jennifer', 'davis', 'jenniferdavis@guvi.in', 'Legal', 25000, '2021-03-25');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('maria', 'miller', 'mariamiller@guvi.in', 'IT', 95000, '2021-03-25');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('susan', 'wilson', 'susanwilson@guvi.in', 'IT', 60000, '2022-03-18');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('margaret', 'moore', 'margaretmoore@guvi.in', 'IT', 25000, '2010-01-12');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('dorothy', 'taylor', 'dorothytaylor@guvi.in', 'IT', 36000, '2015-08-02');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('lisa', 'anderson', 'lisaanderson@guvi.in', 'Human Resources', 25000, '2015-08-02');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('nancy', 'thomas', 'nancythomas@guvi.in', 'Legal', 95000, '2021-03-25');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('karen', 'jackson', 'karenjackson@guvi.in', 'IT', 45000, '2020-09-20');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('betty', 'white', 'bettywhite@guvi.in', 'Legal', 15000, '2021-03-27');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('helen', 'harris', 'helenharris@guvi.in', 'Sales', 25000, '2021-03-04');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('sandra', 'martin', 'sandramartin@guvi.in', 'Sales', 45000, '2021-03-04');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('donna', 'thompson', 'donnathompson@guvi.net', 'Sales', 95000, '2021-03-04');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('carol', 'garcia', 'carolgarcia@guvi.in', 'IT', 36000, '2020-09-20');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('ruth', 'martinez', 'ruthmartinez@guvi.in', 'IT', 60000, '2015-08-02');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('sharon', 'robinson', 'sharonrobinson@guvi.in', 'IT', 95000, '2021-03-04');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('michelle', 'clark', 'michelleclark@guvi.aol', 'IT', 25000, '2021-03-10');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('laura', 'rodriguez', 'laurarodriguez@guvi.in', 'Sales', 45000, '2020-09-20');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('sarah', 'lewis', 'sarahlewis@guvi.in', 'Sales', 25000, '2020-09-20');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('kimberly', 'lee', 'kimberlylee@guvi.com', 'IT', 60000, '2021-03-10');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('deborah', 'walker', 'deborahwalker@guvi.com', 'Human Resources', 25000, '2016-10-31');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('jessica', 'hall', 'jessicahall@guvi.com', 'IT', 25000, '2015-08-02');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('shirley', 'allen', 'shirleyallen@guvi.com', 'IT', 95000, '2015-08-02');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('ramesh', 'yadav', 'rameshyadav@guvi.com', 'Sales', 36000, '2017-05-22');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('angela', 'hernandez', 'angelahernandez@guvi.com', 'Sales', 95000, '2017-05-22');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('melissa', 'king', 'melissaking@guvi.com', 'IT', 45000, '2018-06-30');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('brenda', 'wright', 'brendawright@guvi.com', 'Sales', 95000, '2016-10-31');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('amy', 'lopez', 'amylopez@guvi.net', 'Sales', 15000, '2021-03-10');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('santosh', 'kumar', 'santoshkumar@guvi.com', 'IT', 25000, '2021-03-10');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('rebecca', 'scott', 'rebeccascott@guvi.com', 'Human Resources', 25000, '2016-10-31');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('virginia', 'green', 'virginiagreen@guvi.com', 'IT', 45000, '2012-07-04');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('kathleen', 'adams', 'kathleenadams@guvi.com', 'IT', 95000, '2012-07-04');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('pamela', 'baker', 'pamelabaker@guvi.in', 'IT', 36000, '2018-06-30');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('martha', 'gonzalez', 'marthagonzalez@guvi.com', 'Marketing', 45000, '2018-06-30');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('debra', 'nelson', 'debranelson@guvi.com', 'Marketing', 25000, '2021-03-10');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('amanda', 'carter', 'amandacarter@guvi.org', 'Marketing', 60000, '2022-03-18');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('stephanie', 'mitchell', 'stephaniemitchell@guvi.com', 'Human Resources', 45000, '2022-03-18');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('carolyn', 'perez', 'carolynperez@guvi.com', 'Marketing', 36000, '2012-07-04');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('christine', 'roberts', 'christineroberts@guvi.com', 'Marketing', 60000, '2018-06-30');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('marie', 'turner', 'marieturner@guvi.com', 'Marketing', 25000, '2019-11-25');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('janet', 'phillips', 'janetphillips@guvi.com', 'Media Relations', 45000, '2012-07-04');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('catherine', 'campbell', 'catherinecampbell@guvi.in', 'Media Relations', 36000, '2022-03-18');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('frances', 'parker', 'francesparker@guvi.com', 'Media Relations', 45000, '2012-07-04');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('ann', 'evans', 'annevans@guvi.com', 'Human Resources', 60000, '2019-11-25');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('joyce', 'edwards', 'joyceedwards@guvi.com', 'Media Relations', 45000, '2012-07-04');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('diane', 'collins', 'dianecollins@guvi.com', 'Media Relations', 36000, '2012-07-04');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('diane', 'collins', 'dianecollins@guvi.com', 'Media Relations', 36000, '2012-07-04');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('mary', 'smith', 'marysmith@guvi.com', 'Human Resources', 95000, '2006-02-14');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('diane', 'collins', 'dianecollins@guvi.com', 'Media Relations', 36000, '2012-07-04');
INSERT INTO `worker` (`first_name`, `last_name`, `email`, `department`, `salary`, `joining_date`) VALUES ('mary', 'smith', 'marysmith@guvi.com', 'Human Resources', 95000, '2006-02-14');
